# Generated by Django 6.0.1 on 2026-01-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdbapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mlgenre',
            table='ml_genre',
        ),
        migrations.AlterModelTable(
            name='mlmovie',
            table='ml_movie',
        ),
    ]
