# Generated by Django 6.0.1 on 2026-01-22 11:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdbapi', '0002_alter_mlgenre_table_alter_mlmovie_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mlgenre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_ml_genre_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='mlmovie',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('genre'), name='uniq_ml_movie_title_genre_ci'),
        ),
    ]
