# Generated by Django 6.0.1 on 2026-01-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdbapi', '0003_mlgenre_uniq_ml_genre_name_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmovie',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
