# Generated by Django 6.0.1 on 2026-01-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdbapi', '0004_alter_mlmovie_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmovie',
            name='created_by',
            field=models.CharField(default='system', max_length=255),
            preserve_default=False,
        ),
    ]
